### PR TITLE
drivers: display: Added support for 2.7inch epaper display

### PR DESCRIPTION
**Pull request by DineshDK03**
Added new display driver ek79652

Signed-off-by: Dinesh Kumar K [dinesh@linumiz.com](mailto:dinesh@linumiz.com)

### CODE REVIEW

**Comment by parthitce** [comment]
Removing myself as I can't review this PR due to limited time.

**Comment by parthitce** [comment]
and @DineshDK03 ?

**Comment by ssekar15** [comment]
I paused my review until ELC, will continue soon

**Comment by ssekar15** [comment]
@DineshDK03 what is the plan for this PR!

**Comment by DineshDK03** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/38306#issuecomment-1217196046 this is the last known state of this PR.

**Pull request closed without merging**
